### ISSUE TITLE
Support more date formater

### ISSUE THREAD

**Issue by toreau** [neilb/Date-QuarterOfYear#1]
Ref. https://github.com/neilb/Date-QuarterOfYear/blob/3430b09c5b5f54b0f8938d7293a936c55616f52e/lib/Date/QuarterOfYear.pm#L37; should easily support 2021-2-28, 2021-2-1 etc.

**Comment by neilb** [comment]
Thanks – fixed in the 0.05 release, which is making its way to CPAN.
